# Generated by Django 4.2.2 on 2023-07-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/'),
        ),
    ]
