# Generated by Django 4.2.2 on 2023-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profail',
            name='manzil',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
