# Generated by Django 4.2.2 on 2023-07-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profail_manzil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/rofil/static/img/'),
        ),
    ]
