# Generated by Django 4.2.2 on 2023-07-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profail_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user/profil/static/img/'),
        ),
    ]
