# Generated by Django 4.2.2 on 2023-08-12 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profail'),
            preserve_default=False,
        ),
    ]
